### ISSUE TITLE
Only generates a single day’s trip from multi-day data for generate_json.py

### ISSUE THREAD

**Issue by TriangleMesh** [nickolanack/bcatus-trip-visualizer#2]
It is also uncertain whether the generated JSON data is complete for this single day

**Comment by nickolanack** [comment]
https://github.com/nickolanack/bcatus-trip-visualizer/blob/dac002f4a27fecd6135f20c7bb2027e45adafac8/scripts/generate_json.py#L48

here you are setting the record for an access code, but if that access code already existed in the dict it will be overwritten

there will be many rows in the csv for each access code, normally at least one for each day
